import os

BOT_TOKEN = os.getenv("BOT_TOKEN", "8871468152:AAFuHHHUTQkr3iqY-98U7vz2MwEWa36qKrs")
BOT_USERNAME = os.getenv("BOT_USERNAME", "deckplaybot")
STARTING_LIVES = 3
MAX_PLAYERS = 11
MIN_PLAYERS = 2
TURN_TIME_SECONDS = 60
PASS_REFRESH_THRESHOLD = 3